library tplayx;

uses
  ListsU in '..\ListsU.pas',
  InitCode in 'InitCode.pas',
  InitCode_CoreExePatching in 'InitCode_CoreExePatching.pas',
  LOS_extensions in 'plugins\LOS_extensions.pas',
  LOS_GUIText in 'plugins\LOS_GUIText.pas',
  LOS_Radar in 'plugins\LOS_Radar.pas',
  PluginEngine in 'PluginEngine.pas',
  Plugins in 'Plugins.pas',
  SpeedHack in 'plugins\SpeedHack.pas',
  MultiAILimit in 'plugins\MultiAILimit.pas',
  TA_MemoryLocations in 'TAMem\TA_MemoryLocations.pas',
  logging in '..\logging.pas',
  packet_old in '..\packet_old.pas',
  textdata in '..\textdata.pas',
  MemMappedDataStructure in 'MemMappedDataStructure.pas',
  DPLobbyWrapper in 'DPLobbyWrapper.pas',
  TADemoConsts in 'TADemoConsts.pas',
  Dplayx_exports in 'Dplayx_exports.pas',
  TAMemManipulations in 'TAMem\TAMemManipulations.pas',
  uDebug in '..\uDebug.pas',
  TA_NetworkingMessages in 'netmsgHandling\TA_NetworkingMessages.pas',
  TextFileU in '..\TextFileU.pas',
  PacketBufferU in 'packets\PacketBufferU.pas',
  DPlay in 'DPlay.pas',
  DPLobby in 'DPLobby.pas',
  log2 in 'log2.pas',
  PlayerDataU in 'PlayerDataU.pas',
  CommandHandlerU in 'CommandHandlerU.pas',
  idplay in 'idplay.pas',
  PluginCommandHandlerU in 'plugins\PluginCommandHandlerU.pas',
  InputHook in 'plugins\InputHook.pas',
  threadlogging in 'threadlogging.pas',
  LOS_MiniMapUnits in 'plugins\LOS_MiniMapUnits.pas',
  LOS_UpdateTables in 'plugins\LOS_UpdateTables.pas',
  COB_extensions in 'plugins\COB_extensions.pas',
  LOS_PlayerSeeUnit in 'plugins\LOS_PlayerSeeUnit.pas',
  PauseLock in 'plugins\PauseLock.pas',
  UnitLimit in 'plugins\UnitLimit.pas',
  TA_FunctionsU in 'TAMem\TA_FunctionsU.pas',
  LOS_AllyPlayer in 'plugins\LOS_AllyPlayer.pas',
  ErrorLog_ExtraData in 'plugins\ErrorLog_ExtraData.pas',
  Thread_marshaller in 'plugins\Thread_marshaller.pas',
  IniOptions in 'plugins\IniOptions.pas',
  ModsList in 'ModsList.pas',
  Colors in 'plugins\Colors.pas',
  Builders in 'plugins\Builders.pas',
  KeyboardHook in 'plugins\KeyboardHook.pas',
  TA_MemoryStructures in 'TAMem\TA_MemoryStructures.pas',
  TA_MemoryConstants in 'TAMem\TA_MemoryConstants.pas',
  ConsoleTimer in 'ConsoleTimer.pas',
  StopWatch in 'StopWatch.pas',
  RegPathFix in 'plugins\RegPathFix.pas',
  ResurrectPatrol in 'plugins\ResurrectPatrol.pas',
  ClockPosition in 'plugins\ClockPosition.pas',
  WeaponAimNTrajectory in 'plugins\WeaponAimNTrajectory.pas',
  KillDamage in 'plugins\KillDamage.pas',
  ScriptCallsExtend in 'plugins\ScriptCallsExtend.pas',
  UnitActions in 'plugins\UnitActions.pas',
  TAExceptionsLog in 'plugins\TAExceptionsLog.pas',
  GUIEnhancements in 'plugins\GUIEnhancements.pas',
  statslogging in 'plugins\StatsLogging.pas',
  MinimapExpand in 'plugins\MinimapExpand.pas',
  PlayersSlotsExpand in 'plugins\PlayersSlotsExpand.pas',
  SaveUnitsWeaponsList in 'plugins\SaveUnitsWeaponsList.pas',
  WeaponsExpand in 'plugins\WeaponsExpand.pas',
  UnitInfoExpand in 'plugins\UnitInfoExpand.pas',
  MapExtensions in 'plugins\MapExtensions.pas',
  GAFSequences in 'plugins\GAFSequences.pas',
  BattleRoomEnhancements in 'plugins\BattleRoomEnhancements.pas',
  ExtensionsMem in 'plugins\ExtensionsMem.pas';

{$R *.res}

begin
end.






